---

- name: add APT repo
  apt: add-apt-repository ppa:no1wantdthisname/ppa
  sudo: yes
  
- name: install Infinality and fonts
  apt:
  with_items:
    - ttf-mscorefonts-installer
    - fontconfig-infinality
  shell: /etc/fonts/infinality/infctl.sh setstyle osx
  tags:
    - patches
    - gui
       
